UTILS_DIR=./utils

include $(UTILS_DIR)/message/Makefile
include ${UTILS_DIR}/serial/Makefile
include ${UTILS_DIR}/time/Makefile
include ${UTILS_DIR}/communication/Makefile
# include ${UTILS_DIR}/cpp-linenoise/Makefile

C_INCLUDES += -I$(UTILS_DIR)/time
C_INCLUDES += -I$(UTILS_DIR)/message
C_INCLUDES += -I$(UTILS_DIR)/serial
C_INCLUDES += -I$(UTILS_DIR)/communication
C_INCLUDES += -I$(UTILS_DIR)/cpp-linenoise

