UTILITIES_DIR=./utilities

include $(UTILITIES_DIR)/vlog/Makefile
include ${UTILITIES_DIR}/message/Makefile
include ${UTILITIES_DIR}/BEEP/Makefile
include ${UTILITIES_DIR}/LED/Makefile

C_INCLUDES += -I$(UTILITIES_DIR)/vlog
C_INCLUDES += -I$(UTILITIES_DIR)/message
C_INCLUDES += -I$(UTILITIES_DIR)/BEEP
C_INCLUDES += -I$(UTILITIES_DIR)/LED
C_INCLUDES += -I$(UTILITIES_DIR)/Bit_Band